### ISSUE TITLE
Using maven; result fails to start over java.lang.ClassNotFoundException: org.springframework.context.event.GenericApplicationListener

### ISSUE THREAD

**Issue by paulvi** [szjug/monolith#2]
Using `maven-shade-plugin` 2.3 (the same as in spring inherited poms)
- http://www.mkyong.com/maven/create-a-fat-jar-file-maven-shade-plugin/

Problem `io.github.szjug.shade` project 

```
<dependencies>
    <dependency>
        <groupId>io.github.szjug</groupId>
        <artifactId>io.github.szjug.greeting</artifactId>
        <version>0.1.0</version>
    </dependency>
    <dependency>
        <groupId>io.github.szjug</groupId>
        <artifactId>io.github.szjug.who</artifactId>
        <version>0.1.0</version>
    </dependency>
</dependencies>
```

got maven errors:

```
Missing artifact io.github.szjug:io.github.szjug.greeting:jar:0.1.0
Missing artifact io.github.szjug:io.github.szjug.who:jar:0.1.0
```

Solved by running `mvn install`

**Comment by paulvi** [comment]
```
D:\Workspaces\GitHub\monolith\maven\io.github.szjug.shade\target>java -jar io.github.szjug.shade-0.1.0.jar
Exception in thread "main" java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.
ApplicationListener : org.springframework.boot.logging.ClasspathLoggingApplicationListener
        at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:414)
        at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:394)
        at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:385)
        at org.springframework.boot.SpringApplication.initialize(SpringApplication.java:263)
        at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:237)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
        at io.github.szjug.ShadeApplication.main(ShadeApplication.java:10)
Caused by: java.lang.NoClassDefFoundError: org/springframework/context/event/GenericApplicationListener
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
        at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:407)
        ... 7 more
Caused by: java.lang.ClassNotFoundException: org.springframework.context.event.GenericApplicationListener
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 21 more
```
